### ISSUE TITLE
str not converted into StyleSource implicitly

### ISSUE THREAD

**Issue by xD-prateek** [futursolo/stylist-rs#132]
I am trying out stylist for the first time. As per the tutorials, i should be able to convert `&str` into the required type, but it produces the error given as:
```
the trait `From<&str>` is not implemented for `StyleSource`
```
The error.
![image](https://github.com/futursolo/stylist-rs/assets/110823622/bd876fc9-0516-4b0d-a309-83a340cf6d15)

Following is my code.
````rust
use stylist::{yew::styled_component, Style};

#[styled_component(App)]
pub fn app() -> Html {    
    let style_str = "background-color: red;";
    let stylesheet = Style::new(style_str).unwrap();
    html! {
            <div class={stylesheet}>
                <h1>{"Hello World using stylesheet!"}</h1>
                <p>{"some more text..."}</p>
            </div>
    }
}  

```

**Comment by WorldSEnder** [comment]
Consider the `css!` macro available in a `styled_component` or the [`use_style!`](https://docs.rs/stylist/latest/stylist/yew/macro.use_style.html) hook available in any function component.

Creating a style from a runtime string requires enabling the [`parser`](https://docs.rs/stylist/latest/stylist/#features-flags) feature and is most of the time not what you want.
