### ISSUE TITLE
Yew Function Component Support

### ISSUE THREAD

**Issue by futursolo** [futursolo/stylist-rs#23]
This issue aims to experiment with hooks API that will be adopted with the upcoming function component for Yew 0.19.

**Comment by futursolo** [comment]
There're two sets of APIs that will be introduced:

1. `use_style` and `use_style!` API.
    The function flavour of this hook will accept the same argument as `Style::new` and the macro flavour will accept the same argument as the upcoming procedural macro.

2. `styled_component(MyComponent)` + `css!`

This component will introduce a `styled_component` attribute which will be equivalent to the original `function_component` from yew but also injects a manager instance with `use_context` at the beginning of the function component.


Purposed Syntax:
```rust
use stylist::yew::styled_component;

#[styled_component(MyComponent)]
fn my_component() -> Html {
    html! {
        <div class=css!(r#"color: red;"#)>
            {"Styled Text!"}
        </div>
    }
}
```

Both APIs will be context aware.

**Comment by WorldSEnder** [comment]
I'm currently experimenting with having a branch that tracks yew@next until the release of 0.19. This could then host the hooks implementation.

**Comment by WorldSEnder** [comment]
The working parts live on the [yew-next](https://github.com/futursolo/stylist-rs/tree/yew-next) branch now

**Comment by futursolo** [comment]
I do plan to cut at least one more release before introducing hooks (switching to track `yew` master) so I am fine with it lives on a different branch for now.

**Comment by futursolo** [comment]
As per https://github.com/yewstack/yew/issues/2052, I think the Yew 0.19 release is imminent.

I have update the master branch to track master branch of Yew and implemented the `styled_component` API.

So as soon as Yew 0.19 is released we can release a version with function component support.

**Comment by futursolo** [comment]
The Yewdux and `yewtil::store` example has been replaced with Context API Example.
