### ISSUE TITLE
Consistent AST generation

### ISSUE THREAD

**Issue by futursolo** [futursolo/stylist-rs#32]
Currently, there're two syntaxes that co-exists in the procedural macro: inline syntax and string literals.
At this moment, the codebase of two syntaxes is completely separated.

This issue intends to unify code generation on both syntaxes so both syntaxes yield a consistent generated AST and new features can be landed easier on both syntaxes.

This also removes duplicate logic by increasing the amount of code shared by both syntaxes and hence reduces future maintenance work on the codebase.

**Comment by WorldSEnder** [comment]
If you didn't already start, I'd be happy to do this

**Comment by futursolo** [comment]
Please do so if you have time.

It might not be good to progress in parallel with #31 as that requires changes on the AST, so I will hold off until you finish.

I also need to take a short break from this. So don't feel rushed and progress at your own pace.
