### ISSUE TITLE
Slashes in css seem not allowed

### ISSUE THREAD

**Issue by Madoshakalaka** [futursolo/stylist-rs#39]
```rust
    let css = stylist::css!("grid-row: 3 / span 4";);
    let css = stylist::css!("grid-row: 3/ span 4";);
    let css = stylist::css!("grid-row: 3/span4";);
```
all three lines being valid css, fail to compile.

**Comment by futursolo** [comment]
Thank you for the report.

This is also related to comment handling where comment is not handled properly. We need to get #38 landed first before addressing this issue.
