### ISSUE TITLE
`use stylist::css` missing in the first yew example in the readme

### ISSUE THREAD

**Issue by Madoshakalaka** [futursolo/stylist-rs#58]
```diff
- stylist::yew::styled_component;
+ use stylist::{yew::styled_component, css};
```

and the version is outdated:

```diff
- stylist = "0.9"
+ stylist = "0.10"
```

**Comment by futursolo** [comment]
> You don’t need to import `css!` inside of a `styled_component`.

See: https://docs.rs/stylist/0.10.0/stylist/yew/attr.styled_component.html#note

It's true that the version needs to be updated.
