### ISSUE TITLE
the trait bound `yew::Classes: From<StyleSource>` is not satisfied

### ISSUE THREAD

**Issue by simbleau** [futursolo/stylist-rs#86]
Title.

Due to https://github.com/yewstack/yew/issues/2848, I am forced to upgrade to master.

Unfortunately I rely heavily on stylist, and in master `<div class={ css!(..) } />` no longer compiles, since `the trait bound yew::Classes: From<StyleSource> is not satisfied`

**Comment by futursolo** [comment]
Currently, stylist depends on 0.19 which is not compatible with `master`.

You can track the progress in #69.

BTW, you can use `use_location` to listen to location changes in both Yew 0.19 and master.

**Comment by simbleau** [comment]
D'oh! I thought use_location was only in master. :) +1
