### ISSUE TITLE
Feature request: get component identifier from function name if PascalCase

### ISSUE THREAD

**Issue by allan2** [futursolo/stylist-rs#90]
Thanks @futursolo and @WorldSEnder for this crate!

It would be nice if the attribute name could be omitted, like in Yew 0.20. #69 maybe relevant?

Current:

```rs
#[styled_component](MyStyledComponent)
fn my_styled_component() -> Html {
    html! {<div class={css!("color: red;")}>{"Hello World!"}</div>}
}
```

Proposed:
```rs
#[styled_component]
fn MyStyledComponent() -> Html {
    html! {<div class={css!("color: red;")}>{"Hello World!"}</div>}
}
```

**Comment by futursolo** [comment]
Yes, this will be supported after we update stylist to Yew 0.20.

> It would be nice if the attribute name could be omitted, like in Yew 0.20. https://github.com/futursolo/stylist-rs/pull/69 maybe relevant?

`#[styled_component]` is a wrapper around `#[function_component]`.
But the attribute parsing is separate so it will need to be updated manually.

#69 currently does not contain an update that supports function component without attribute name.
