### ISSUE TITLE
Loading from css file

### ISSUE THREAD

**Issue by amiyatulu** [futursolo/stylist-rs#97]
Loading from css file gives error in  version stylist = { version = "0.11.0", features=["yew"]}

let stylesheet = Style::new(STYLE_FILE).unwrap();
   |                      ^^^^^^^^^^ the trait `From<&str>` is not implemented for `StyleSource`

Its gives no error on version="0.10.0"

```
const STYLE_FILE: &str = include_str!("fileupload.css");
#[styled_component(FileUpload)]
pub fn file_upload() -> Html {
    let stylesheet = Style::new(STYLE_FILE).unwrap();
```

**Comment by WorldSEnder** [comment]
As mentioned in the release notes, the `parser` feature is now disabled by default. You should be able to use

```
stylist = { version = "0.11.0", features = ["yew", "parser"] }
```

 to dynamically load css from strings.
